### ISSUE TITLE
Use input dataset from a smartphone mounted to a bicycle

### ISSUE THREAD

**Issue by Robinlovelace** [vsimko/rroad#13]
Would your package be able to estimate surface roughness based on data from a smartphone on a bicycle do you think? Thanks for publishing it in the open!

**Comment by vsimko** [comment]
If I remember correctly, the implemented code assumes a particular car model. See **page 252** (pdf page 264) in this PDF http://documents.worldbank.org/curated/en/326081468740204115/pdf/multi-page.pdf

**Comment by Robinlovelace** [comment]
Could the parameters be adjusted to work for different types of vehicle? I would imagine so. I will ask some colleagues interested in the topic in Leeds. Thanks for quick and collaborative reply.

**Comment by kelaub** [comment]
The package is intended to determine the International Roughness Index (IRI), which is a rather prominent metric for describing the roughness of a specific (road) profile.

In your case, you can either define a physical model representing your bike and smartphone and its response to the roughness on the road, or you can apply a generic machine learning algorithm to obtain an estimate of the roughness using the sensor readings from your smartphone as features.

We have shown how the latter approache – based on machine learning (ML) – can be applied here https://aisel.aisnet.org/icis2016/DataScience/Presentations/20/
or here https://scholarspace.manoa.hawaii.edu/handle/10125/41344

With these ML-based approache, you should note that you need some kind of ground truth data (e.g. the actual profile of the surface of a training road or its roughness indices). If you only have one of these, you can use this package to derive the other one.

**Comment by Robinlovelace** [comment]
Hi @kelaub, that is an excellent reply suggesting that this package may not be the solution. The papers you link to look fascinating and have the potential to resolve my intended use case so closing the issue. If you know of any high quality and reproducible research (much research is neither) applying such methods to data derived from smartphones on handlebars, please do comment here and tag me.

**Comment by kelaub** [comment]
It totally makes sense for me to do some research in the existing literature about the use case with a bicycle. If you do not succeed in finding sound, use case specific papers, you can definitely follow our generic approach described in the papers mentioned above. The physics of the vehicle (whether bicycle or car) should be estimated by the ML approach.
