### ISSUE TITLE
Solve seewave dependency which hinders installation of rroad

### ISSUE THREAD

**Issue by kelaub** [vsimko/rroad#2]
installing rroad causes following error:
"installation of package ‘seewave’ had non-zero exit status"

**Comment by vsimko** [comment]
I cannot reproduce the bug on my machine (Linux Mint). Perhaps this is a bug in `seewave` package.

**Comment by vsimko** [comment]
I noticed the same problem on Travis.
The error was:

```
gcc -std=gnu99 -I/home/travis/R-bin/lib/R/include -DNDEBUG  -I/home/travis/R-bin/include    -fpic  -g -O2  -c stft.c -o stft.o
stft.c:3:61: fatal error: sndfile.h: No such file or directory
compilation terminated.
make: *** [stft.o] Error 1
ERROR: compilation failed for package â€˜seewaveâ€™
* removing â€˜/usr/local/lib/R/site-library/seewaveâ€™
```

Then, I searched for linux package which contains `sndfile.h`:

``` sh
> apt-file search sndfile.h
```

and among the results, there was:

```
libsndfile1-dev: /usr/include/sndfile.h
```

I updated the `.travis.yml` file and added `libsndfile1-dev` as apt requirement

**Comment by vsimko** [comment]
Another problem with `fftw3.h`:
`apt-file search fftw3.h` found `libfftw3-dev`
